---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  generation: 7
  name: jenkins
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: quay.io/openshift/origin-jenkins:latest
    generation: 3
    importPolicy: {}
    name: "latest"
    referencePolicy:
      type: Source
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  generation: 7
  name: custom-jenkins
spec:
  lookupPolicy:
    local: false

